import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const systemDesigns = [
    {
        id: "rate-limiter",
        title: "Rate Limiter Design",
        explanation: "A scalable, distributed rate-limiting service designed to protect downstream resources from traffic surges.",
        breakdown: "Token Bucket algorithm implemented via Redis for atomic counter operations and low latency (sub-ms).",
        flow: "Client Request → API Gateway → Rate Limit Service (Redis) → Upstream Service.",
        scaling: "Horizontal scaling of the rate-limit service nodes; Redis Cluster for high availability and data partitioning."
    },
    {
        id: "url-shortener",
        title: "URL Shortener",
        explanation: "A high-read throughput system for shortening and redirecting URLs globally.",
        breakdown: "Base62 encoding of unique IDs generated by a distributed ID service (Snowflake).",
        flow: "POST /shorten → ID Gen → Store in DB & Cache → Return Short Link. GET /xyz → Cache Look-up → 302 Redirect.",
        scaling: "Read-aside caching with multiple Redis read replicas; Database sharding by short-code hash."
    },
    {
        id: "notification",
        title: "Notification Service",
        explanation: "A cross-channel (Push, SMS, Email) notification engine with prioritization and retry logic.",
        breakdown: "Topic-based message queuing using Kafka for decoupling producers from delivery providers.",
        flow: "Trigger Event → Service → Kafka Topic → Consumer Workers → Provider Gateway (Twilio/SES).",
        scaling: "Partitioned Kafka topics for parallel processing; Dead Letter Queues (DLQ) for failure handling."
    },
    {
        id: "portfolio-engine",
        title: "Resume Engine Architecture",
        explanation: "The architecture behind ShowWork, focused on dynamic multi-tenancy and high-fidelity generation.",
        breakdown: "Hybrid cloud approach with edge functions for UI and specialized workers for PDF/Site generation.",
        flow: "User Data Edits → API → State Store → Worker Queue → Asset Generation → CDN Propagation.",
        scaling: "Serverless workers for on-demand generation; Geo-distributed asset storage (S3) and CDN (Cloudfront)."
    }
];

export const SystemDesign: React.FC = () => {
    const [activeTab, setActiveTab] = useState(systemDesigns[0].id);

    return (
        <section id="system-design" className="py-12">
            <div className="flex flex-col gap-4 mb-16">
                <h3 className="text-sm font-semibold text-blue-500 uppercase tracking-widest">Thinking</h3>
                <h2 className="text-3xl lg:text-4xl font-bold text-white tracking-tight">System Design Patterns</h2>
            </div>

            <div className="flex flex-col lg:flex-row gap-12 items-start">
                {/* Tab Selectors */}
                <div className="flex lg:flex-col flex-wrap gap-2 lg:w-72">
                    {systemDesigns.map((design) => (
                        <button
                            key={design.id}
                            onClick={() => setActiveTab(design.id)}
                            className={`px-6 py-4 rounded-xl text-left text-sm font-bold transition-all border ${activeTab === design.id
                                    ? "bg-blue-600/10 border-blue-500/50 text-blue-400"
                                    : "bg-transparent border-transparent text-slate-500 hover:text-slate-300 hover:bg-slate-800/30"
                                }`}
                        >
                            {design.title}
                        </button>
                    ))}
                </div>

                {/* Tab Content */}
                <div className="flex-grow bg-slate-800/20 border border-slate-700/30 rounded-3xl p-8 lg:p-12 min-h-[400px]">
                    <AnimatePresence mode="wait">
                        <motion.div
                            key={activeTab}
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -20 }}
                            transition={{ duration: 0.3 }}
                            className="space-y-10"
                        >
                            <div className="space-y-4">
                                <h4 className="text-2xl font-bold text-white tracking-tight">
                                    {systemDesigns.find(d => d.id === activeTab)?.title}
                                </h4>
                                <p className="text-slate-300 text-lg leading-relaxed">
                                    {systemDesigns.find(d => d.id === activeTab)?.explanation}
                                </p>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                                <div className="space-y-3">
                                    <span className="text-xs font-bold uppercase tracking-widest text-blue-500/60">Service Breakdown</span>
                                    <p className="text-slate-400 text-sm leading-relaxed">
                                        {systemDesigns.find(d => d.id === activeTab)?.breakdown}
                                    </p>
                                </div>
                                <div className="space-y-3">
                                    <span className="text-xs font-bold uppercase tracking-widest text-blue-500/60">Data Flow</span>
                                    <p className="text-slate-400 text-sm leading-relaxed">
                                        {systemDesigns.find(d => d.id === activeTab)?.flow}
                                    </p>
                                </div>
                            </div>

                            <div className="pt-8 border-t border-slate-700/50">
                                <div className="space-y-3">
                                    <span className="text-xs font-bold uppercase tracking-widest text-blue-500/60">Scaling Considerations</span>
                                    <p className="text-slate-300 text-sm font-medium leading-relaxed">
                                        {systemDesigns.find(d => d.id === activeTab)?.scaling}
                                    </p>
                                </div>
                            </div>
                        </motion.div>
                    </AnimatePresence>
                </div>
            </div>
        </section>
    );
};
