import React from 'react';
import { Mail, Github, Linkedin, ExternalLink, Cpu, Globe } from 'lucide-react';

interface ResumeModernProps {
    userData: any;
    projects: any[];
}

export const ResumeModern: React.FC<ResumeModernProps> = ({ userData, projects }) => {
    return (
        <div className="w-full h-full bg-slate-50 flex font-sans">
            {/* Sidebar */}
            <aside className="w-[280px] bg-slate-800 text-slate-100 flex flex-col p-10">
                <div className="mb-12">
                    <h1 className="text-3xl font-bold mb-2 tracking-tight">{userData.name}</h1>
                    <p className="text-indigo-400 font-medium uppercase text-xs tracking-[0.2em]">
                        {userData.title || 'Software Developer'}
                    </p>
                </div>

                <div className="space-y-8 flex-1">
                    {/* Contact info in sidebar */}
                    <div className="space-y-4">
                        <h3 className="text-[11px] font-black uppercase text-slate-500 tracking-widest border-b border-slate-700 pb-2">Contact</h3>
                        <div className="space-y-3 text-[13px] opacity-80">
                            <div className="flex items-center gap-2">
                                <Mail className="w-3.5 h-3.5" />
                                <span className="truncate">{userData.email || 'your.email@example.com'}</span>
                            </div>
                            {userData.socialLinks?.github && (
                                <div className="flex items-center gap-2">
                                    <Github className="w-3.5 h-3.5" />
                                    <span>github.com/{userData.socialLinks.github}</span>
                                </div>
                            )}
                            {userData.socialLinks?.linkedin && (
                                <div className="flex items-center gap-2">
                                    <Linkedin className="w-3.5 h-3.5" />
                                    <span>linkedin.com/in/{userData.socialLinks.linkedin}</span>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Expertise/Skills in sidebar */}
                    <div>
                        <h3 className="text-[11px] font-black uppercase text-slate-500 tracking-widest border-b border-slate-700 pb-2 mb-4">Expertise</h3>
                        <div className="flex flex-wrap gap-2">
                            {(userData.techStack || userData.skills || []).map((skill: any, i: number) => (
                                <span key={i} className="bg-slate-700 text-slate-200 px-2 py-0.5 rounded text-[10px] font-medium">
                                    {typeof skill === 'string' ? skill : skill.name}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>

                <div className="mt-12 opacity-40 text-[10px] font-mono">
                    GENERATED BY SHOWWORK
                </div>
            </aside>

            {/* Main Content */}
            <main className="flex-1 bg-white p-12 text-slate-800">
                {/* Summary Section */}
                <section className="mb-12">
                    <h3 className="text-lg font-bold text-slate-900 mb-4 border-l-4 border-indigo-600 pl-4">Professional Summary</h3>
                    <p className="text-sm text-slate-600 leading-relaxed">
                        {userData.bio || 'Dynamic and detail-oriented developer dedicated to creating high-quality, efficient software solutions. Passionate about innovation and constant improvement in the tech space.'}
                    </p>
                </section>

                {/* Key Projects Section */}
                <section className="mb-12">
                    <h3 className="text-lg font-bold text-slate-900 mb-6 border-l-4 border-indigo-600 pl-4">Key Projects</h3>
                    <div className="space-y-8">
                        {projects.slice(0, 3).map((project, i) => (
                            <div key={i} className="relative">
                                <div className="flex justify-between items-start mb-2">
                                    <h4 className="text-base font-bold text-slate-900 group flex items-center gap-2">
                                        {project.name}
                                        <ExternalLink className="w-3 h-3 text-slate-300 opacity-0 transition-opacity" />
                                    </h4>
                                    <div className="flex gap-2">
                                        {project.technologies?.slice(0, 3).map((tech: string, idx: number) => (
                                            <span key={idx} className="text-[9px] font-bold text-indigo-600 bg-indigo-50 px-1.5 py-0.5 rounded uppercase">
                                                {tech}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                                <p className="text-[13px] text-slate-600 mb-3">{project.description}</p>
                            </div>
                        ))}
                    </div>
                </section>

                {/* Other Info/Note */}
                <section className="mt-auto pt-12 border-t border-slate-100 italic text-[11px] text-slate-400">
                    * Additional experience and education details can be retrieved from my full portfolio.
                </section>
            </main>
        </div>
    );
};
